import type { JourneyScenario, JourneyStage, LayerLens } from '../schema/journeyScenarioSchema'

export type ObserverId = 'user' | 'browser' | 'client-os' | 'switch' | 'router' | 'dns' | 'proxy' | 'app' | 'db'
export type ObserverProfile = { id: ObserverId; icon: string; label: string; shortLabel: string; stageRoles: JourneyStage['device']['role'][]; lenses: LayerLens[]; canSee: string[]; cannotAssume: string[]; typicalEvidence: string[]; mentalModel: string }
export const observerProfiles: ObserverProfile[] = [
  { id:'user', icon:'👤', label:'User', shortLabel:'User', stageRoles:['user'], lenses:['human'], canSee:['URL text','loading/waiting state','browser error page','rendered content'], cannotAssume:['DNS packets','TCP flags','TLS records','MAC addresses'], typicalEvidence:['screenshot','reported error text','time of symptom'], mentalModel:'The user sees destination and outcome, not the roads underneath.' },
  { id:'browser', icon:'🌐', label:'Browser', shortLabel:'Browser', stageRoles:['browser'], lenses:['human','application','tls'], canSee:['URL','HTTP request/response','certificate status','render lifecycle'], cannotAssume:['switch MAC table','router NAT internals','raw PHY signal'], typicalEvidence:['DevTools Network tab','browser console','certificate details'], mentalModel:'The browser speaks web semantics and asks the OS to move bytes.' },
  { id:'client-os', icon:'💻', label:'Client OS', shortLabel:'OS', stageRoles:['os','nic'], lenses:['transport','network','link'], canSee:['sockets','ports','routes','ARP/neighbor table','local interface state'], cannotAssume:['remote app logs','reverse proxy upstream state','database result'], typicalEvidence:['ip route','ip neigh','ss','tcpdump'], mentalModel:'The OS turns application wishes into network actions.' },
  { id:'switch', icon:'🔀', label:'LAN Switch', shortLabel:'Switch', stageRoles:['switch'], lenses:['link','physical'], canSee:['source MAC','destination MAC','ingress/egress port','VLAN/local segment'], cannotAssume:['HTTP path','TLS content','website URL','database result'], typicalEvidence:['MAC table','port counters','VLAN config'], mentalModel:'The switch moves frames between local doors.' },
  { id:'router', icon:'🧭', label:'Router / NAT / Firewall', shortLabel:'Router', stageRoles:['router','firewall'], lenses:['transport','network'], canSee:['IP addresses','ports','NAT mapping','routing decision'], cannotAssume:['plain HTTPS body','browser DOM','backend DB rows'], typicalEvidence:['routing table','NAT state','firewall logs','conntrack'], mentalModel:'The router forwards by address and may rewrite the return label.' },
  { id:'dns', icon:'📇', label:'DNS Resolver', shortLabel:'DNS', stageRoles:['dns'], lenses:['application','transport','network'], canSee:['queried name','record type','DNS answer'], cannotAssume:['whether TCP/TLS/HTTP later succeeds','page content'], typicalEvidence:['resolver logs','dig output','DNS response code'], mentalModel:'DNS is a phonebook: it gives an address, not the website.' },
  { id:'proxy', icon:'🚪', label:'Reverse Proxy', shortLabel:'Proxy', stageRoles:['proxy'], lenses:['application','tls','transport','network'], canSee:['client connection','TLS termination','HTTP after decrypt','upstream target','status code'], cannotAssume:['user screen','switch-only failures','DB internals unless logged'], typicalEvidence:['access log','error log','TLS config','upstream timing'], mentalModel:'The proxy is the front door routing traffic inside.' },
  { id:'app', icon:'⚙️', label:'Application Server', shortLabel:'App', stageRoles:['app'], lenses:['application'], canSee:['route handler','request context','business logic','dependency calls'], cannotAssume:['client ARP table','switch flooding','raw TLS handshake'], typicalEvidence:['application logs','trace id','exception stack'], mentalModel:'The app decides what answer should be produced.' },
  { id:'db', icon:'🗄️', label:'Database', shortLabel:'DB', stageRoles:['db'], lenses:['application'], canSee:['query text/plan','locks','rows touched','DB errors'], cannotAssume:['browser URL bar','DNS answer','TCP handshake'], typicalEvidence:['query log','slow query log','DB metrics'], mentalModel:'The DB sees data requests, not the whole Internet path.' },
]
export function getObserverProfile(id: string): ObserverProfile { return observerProfiles.find(o => o.id === id) ?? observerProfiles[0] }
export function stageMatchesObserver(stage: JourneyStage, observerId: string): boolean { const o=getObserverProfile(observerId); return o.stageRoles.includes(stage.device.role) || o.lenses.some(l => stage.layerFocus.includes(l)) }
export function getObserverStageIds(scenario: JourneyScenario, observerId: string): string[] { return scenario.stages.filter(s => stageMatchesObserver(s, observerId)).map(s => s.id) }
