import type { JourneyStage, LayerLens } from '../schema/journeyScenarioSchema'
export type FieldTreeNode = { id: string; label: string; lens: LayerLens; value?: string; children: FieldTreeNode[] }
function value(v: unknown): string | undefined { if(v===undefined||v===null||v==='') return undefined; if(Array.isArray(v)) return v.join(', '); if(typeof v==='object') return JSON.stringify(v); return String(v) }
function node(id:string,label:string,lens:LayerLens,val?:unknown,children:FieldTreeNode[]=[]):FieldTreeNode { return {id,label,lens,value:value(val),children} }
export function buildFieldTree(stage: JourneyStage): FieldTreeNode[] { const a=stage.addresses??{}; const reps=stage.representations; const tree: FieldTreeNode[]=[]
  tree.push(node('human','Human interpretation','human',undefined,[node('human-visible','Visible meaning','human',reps.human?.label??stage.copy.whatUserSees),node('human-trap','Common trap','human',stage.copy.easyToConfuse)]))
  if(reps.http||stage.layerFocus.includes('application')) tree.push(node('application','Application / HTTP / DNS','application',undefined,[node('app-summary','Application meaning','application',stage.copy.samePayloadHereLooksLike),...Object.entries(reps.http??{}).map(([k,v])=>node(`http-${k}`,k,'application',v))]))
  if(reps.tls||stage.layerFocus.includes('tls')) tree.push(node('tls','TLS','tls',undefined,[node('tls-purpose','Purpose','tls','Security wrapper / protected channel'),...Object.entries(reps.tls??{}).map(([k,v])=>node(`tls-${k}`,k,'tls',v))]))
  if(reps.tcp||a.srcPort||a.dstPort||stage.layerFocus.includes('transport')) tree.push(node('transport','TCP / UDP','transport',undefined,[node('src-port','Source port','transport',a.srcPort),node('dst-port','Destination port','transport',a.dstPort),node('nat-src-port','NAT source port','transport',a.natSrcPort),...Object.entries(reps.tcp??{}).map(([k,v])=>node(`tcp-${k}`,k,'transport',v))]))
  if(reps.ip||a.srcIp||a.dstIp||stage.layerFocus.includes('network')) tree.push(node('network','IPv4 packet','network',undefined,[node('src-ip','Source IP','network',a.srcIp),node('dst-ip','Destination IP','network',a.dstIp),node('nat-src-ip','NAT source IP','network',a.natSrcIp),...Object.entries(reps.ip??{}).map(([k,v])=>node(`ip-${k}`,k,'network',v))]))
  if(reps.ethernet||a.srcMac||a.dstMac||stage.layerFocus.includes('link')) tree.push(node('link','Ethernet / local link','link',undefined,[node('src-mac','Source MAC','link',a.srcMac),node('dst-mac','Destination MAC','link',a.dstMac),...Object.entries(reps.ethernet??{}).map(([k,v])=>node(`eth-${k}`,k,'link',v))]))
  if(reps.bits||reps.signal||stage.layerFocus.includes('physical')) tree.push(node('physical','Bits / signal','physical',undefined,[...Object.entries(reps.bits??{}).map(([k,v])=>node(`bits-${k}`,k,'physical',v)),...Object.entries(reps.signal??{}).map(([k,v])=>node(`signal-${k}`,k,'physical',v))]))
  return tree }
export function countTreeNodes(nodes: FieldTreeNode[]): number { return nodes.reduce((sum,n)=>sum+1+countTreeNodes(n.children),0) }
